PROG_NAME=storage
PROG_HS_FILES=storage.hs Hos/Storage.hs Hos/Storage/Msg.hs
PROG_LIB_HS_FILES=Hos/Storage/Msg.hs
PROG_CFLAGS=
PROG_JHC_FLAGS=-pinit

include ../build-prog.mk
include ../build-prog-lib.mk
